//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Nomina
    {
        public int ID { get; set; }

        [Display(Name = "Monto total")]
        public Nullable<decimal> Monto_Total { get; set; }

        [Display(Name = "Empleado")]
        public Nullable<int> FK_Empleado { get; set; }

        [Display(Name = "Día")]
        public string Dia { get; set; }

        [Required]
        [Display(Name = "Mes")]
        public string Mes { get; set; }

        [Required]
        [Display(Name = "Año")]
        public string Año { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
