//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vacaciones
    {
        public int ID { get; set; }

        public Nullable<int> FK_Empleado { get; set; }

        [Required]
        [Display(Name = "Motivo")]
        public string Comentario { get; set; }

        [Required]
        [Display(Name = "Hasta")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Entrada { get; set; }

        [Required]
        [Display(Name = "Desde")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
